feat: support pnpm to install and remove packages
adonisjs/sink pull request #19
Opened 2021-11-17 09:14 UTC by RomainLanz

Hey! 👋🏻 

This PR add the support of `pnpm` to manage the `package.json` file

This support has [already been added to mrm](https://github.com/sapegin/mrm/commit/8d976d89a8c184e183edb96d281af0a823530010), therefore only small changes was needed on our side.

This PR contains breaking change, since the `useYarn` method has been renamed to `useClient`.
We could keep the `useYarn` method for backward compatibility if needed.

2021-11-18 02:04 UTC, thetutlage commented
How about still keeping the `useYarn` method and deprecating it?

2021-11-18 02:04 UTC, thetutlage requested changes

2021-11-18 02:04 UTC, thetutlage commented on src/Files/Special/PackageJson.ts
> +  private specificPackageManager: SupportedPackageManager
Can we rename this to just `packageManager`?

2021-11-18 08:17 UTC, RomainLanz commented
> How about still keeping the `useYarn` method and deprecating it?

Yes, I believe it is better to avoid any error we may have not consider.

I have added the `@deprecated` JSDoc on this method, this will allow VSCode (or other IDE) to warn the user about the deprecation.

Since this is a module use internally, I do not believe we should output something to the logger to warn people about it.

Also, I have kept the same function signature to avoid any TypeScript error in old code.

2021-11-20 03:16 UTC, merged

2021-11-20 03:16 UTC, thetutlage commented
Looks good 👍